site_name: Pokemon Umbral Stasis
site_url: https://justpauw.github.io/pokemon-umbral-stasis
site_description: 'Wiki for the Fan Game: Pokemon Umbral Stasis'
site_author: justPauw
repo_url: https://github.com/justPauw/pokemon-umbral-stasis
theme:
  name: material
  features:
  - content.tabls.links
  - content.tooltips
  favicon: img/items/premier-ball.png
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: black
    scheme: default
    toggle:
      icon: material/eye-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: black
    scheme: slate
    toggle:
      icon: material/eye
      name: Switch to light mode
nav:
- Home: index.md
- Item Locations: item_locations.md
- Item Changes: item_changes.md
- Ability Changes: ability_changes.md
- Pokemon:
  - 001 - Pidgey: pokemon/001-pidgey.md
  - 002 - Pidgeotto: pokemon/002-pidgeotto.md
  - 003 - Pidgeot: pokemon/003-pidgeot.md
  - 004 - Zigzagoon: pokemon/004-zigzagoon.md
  - 005 - Linoone: pokemon/005-linoone.md
  - 006 - Starly: pokemon/006-starly.md
  - 007 - Staravia: pokemon/007-staravia.md
  - 008 - Staraptor: pokemon/008-staraptor.md
  - 009 - Taillow: pokemon/009-taillow.md
  - 010 - Swellow: pokemon/010-swellow.md
  - 011 - Sentret: pokemon/011-sentret.md
  - 012 - Furret: pokemon/012-furret.md
  - 013 - Rattata: pokemon/013-rattata.md
  - 014 - Raticate: pokemon/014-raticate.md
  - 015 - Buneary: pokemon/015-buneary.md
  - 016 - Umbral-lopunny: pokemon/016-umbral-lopunny.md
  - 016 - Lopunny: pokemon/016-lopunny.md
  - 017 - Caterpie: pokemon/017-caterpie.md
  - 018 - Metapod: pokemon/018-metapod.md
  - 019 - Butterfree: pokemon/019-butterfree.md
  - 020 - Weedle: pokemon/020-weedle.md
  - 021 - Kakuna: pokemon/021-kakuna.md
  - 022 - Beedrill: pokemon/022-beedrill.md
  - 023 - Wurmple: pokemon/023-wurmple.md
  - 024 - Silcoon: pokemon/024-silcoon.md
  - 025 - Beautifly: pokemon/025-beautifly.md
  - 026 - Cascoon: pokemon/026-cascoon.md
  - 027 - Dustox: pokemon/027-dustox.md
  - 028 - Panpour: pokemon/028-panpour.md
  - 029 - Simipour: pokemon/029-simipour.md
  - 030 - Pansage: pokemon/030-pansage.md
  - 031 - Simisage: pokemon/031-simisage.md
  - 032 - Pansear: pokemon/032-pansear.md
  - 033 - Simisear: pokemon/033-simisear.md
  - 034 - Paras: pokemon/034-paras.md
  - 035 - Parasect: pokemon/035-parasect.md
  - 036 - Ekans: pokemon/036-ekans.md
  - 037 - Arbok: pokemon/037-arbok.md
  - 038 - Stunky: pokemon/038-stunky.md
  - 039 - Skuntank: pokemon/039-skuntank.md
  - 040 - Spinarak: pokemon/040-spinarak.md
  - 041 - Ariados: pokemon/041-ariados.md
  - 042 - Poochyena: pokemon/042-poochyena.md
  - 043 - Umbral-mightyena: pokemon/043-umbral-mightyena.md
  - 043 - Mightyena: pokemon/043-mightyena.md
  - 044 - Hoothoot: pokemon/044-hoothoot.md
  - 045 - Noctowl: pokemon/045-noctowl.md
  - 046 - Cottonee: pokemon/046-cottonee.md
  - 047 - Umbral-whimsicott: pokemon/047-umbral-whimsicott.md
  - 047 - Whimsicott: pokemon/047-whimsicott.md
  - 048 - Venipede: pokemon/048-venipede.md
  - 049 - Whirlipede: pokemon/049-whirlipede.md
  - 050 - Scolipede: pokemon/050-scolipede.md
- Routes:
  - Vinview Town: routes/Vinview Town.md
  - Route 1: routes/Route 1.md
  - Darkroot Forest: routes/Darkroot Forest.md
  - Deeper Darkroot: routes/Deeper Darkroot.md
  - Brightroot Clearing: routes/Brightroot Clearing.md
  - Sowset Town: routes/Sowset Town.md
  - Route 2: routes/Route 2.md
  - Rubble Cave 1F: routes/Rubble Cave 1F.md
  - Rubble Cave B1F: routes/Rubble Cave B1F.md
  - Rubble Cave 2F: routes/Rubble Cave 2F.md
  - Rubble Cave 3F: routes/Rubble Cave 3F.md
  - Southern Oradea: routes/Southern Oradea.md
  - Oradea Town: routes/Oradea Town.md
  - Route 3: routes/Route 3.md
  - Tinspire City: routes/Tinspire City.md
  - Lake Sinew: routes/Lake Sinew.md
  - Lakeview Tunnel: routes/Lakeview Tunnel.md
  - Route 4: routes/Route 4.md
  - Flairtooth Cave: routes/Flairtooth Cave.md
  - Route 5: routes/Route 5.md
  - Baby Garden Central: routes/Baby Garden Central.md
  - Baby Garden West: routes/Baby Garden West.md
  - Baby Garden East: routes/Baby Garden East.md
  - Entree Garden Central: routes/Entree Garden Central.md
  - Entree Garden West: routes/Entree Garden West.md
  - Entree Garden North: routes/Entree Garden North.md
  - Entree Garden East: routes/Entree Garden East.md
  - Flower Garden: routes/Flower Garden.md
  - Hauntill Town: routes/Hauntill Town.md
  - Ethereal Tower F2: routes/Ethereal Tower F2.md
  - Ethereal Tower F3: routes/Ethereal Tower F3.md
  - Ethereal Tower F4: routes/Ethereal Tower F4.md
  - Ethereal Tower F5: routes/Ethereal Tower F5.md
  - Ethereal Tower F6: routes/Ethereal Tower F6.md
  - Route 6: routes/Route 6.md
  - Atropine Woods: routes/Atropine Woods.md
  - Deeper Atropine: routes/Deeper Atropine.md
  - Route 7: routes/Route 7.md
  - Scarlet Descent: routes/Scarlet Descent.md
  - Scarlet Descent 1F: routes/Scarlet Descent 1F.md
  - Scarlet Descent B1F: routes/Scarlet Descent B1F.md
  - Scarlet Descent B2F: routes/Scarlet Descent B2F.md
  - Scarlet Descent B3F: routes/Scarlet Descent B3F.md
  - Flammah Town: routes/Flammah Town.md
  - Seapearl City: routes/Seapearl City.md
  - Route 10: routes/Route 10.md
  - Route 17: routes/Route 17.md
plugins:
- search:
    lang: en
markdown_extensions:
- admonition
- abbr
- attr_list
- md_in_html
- def_list
- pymdownx.tasklist:
    custom_checkbox: true
    clickable_checkbox: true
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.details
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
extra_css:
- stylesheets/extra.css
